# This is a basic workflow to help you get started with Actions

name: Deploy!!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Declare some variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          STR=$(cat test.txt)
          SUB='Linux'
          if [[ "$STR" == *"$SUB"* ]]; then
            echo "Successfully ran test. The file looks okay."
            exit 0
          fi
          exit 1
      - uses: someimportantcompany/github-actions-slack-message@v1
        id: slack
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: Deploy started for ${{ github.sha }}
          color: good # Slack already-supported color